---

- name: delete repository if exists
  file:
    path: /root/sor_tt_code
    state: absent

- name:  Clone repository
  shell: git clone https://github.com/rsolovev/sor_tt_code  /root/sor_tt_code

- name: Build image
  shell: docker build -t time_app:latest /root/sor_tt_code

- name: Stop existing container if exists
  shell: docker stop time_app_1 || true && docker rm time_app_1 || true

- name: Run container
  shell: docker run -d -p 80:80 --name time_app_1 time_app 
