---

- name: delete repository if exists
  file:
    path: /root/sor_tt_code
    state: absent

- name:  Clone repository
  shell: git clone https://github.com/rsolovev/sor_tt_code  /root/sor_tt_code

- name: Build image
  shell: docker build -t time_app:latest /root/sor_tt_code

- name: Run compose
  shell: chdir=/root/sor_tt_code docker-compose up -d --scale time_app=2
